# Generated by Django 5.1.7 on 2025-03-17 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
