# Generated by Django 5.1.7 on 2025-03-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_questionmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='polls.questionmodel'),
        ),
    ]
