# Generated by Django 5.1.7 on 2025-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choicemodel_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='choice',
            field=models.CharField(max_length=20),
        ),
    ]
