# Generated by Django 5.1.7 on 2025-03-19 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choicemodel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
