# Generated by Django 5.1.6 on 2025-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
            ],
        ),
    ]
