# Generated by Django 5.1.7 on 2025-03-17 09:06

import basic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[basic.validators.validate_name])),
                ('description', models.TextField()),
                ('price', models.IntegerField(validators=[basic.validators.validate_number])),
                ('quantity', models.IntegerField(default=1, validators=[basic.validators.validate_number, basic.validators.validate_quantity])),
            ],
        ),
    ]
