# Generated by Django 5.1.7 on 2025-03-11 07:36

import basic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[basic.validators.validate_name])),
                ('description', models.TextField()),
                ('price', models.IntegerField(validators=[basic.validators.validate_number])),
            ],
        ),
    ]
