# Generated by Django 5.1.7 on 2025-03-12 04:44

import basic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, validators=[basic.validators.validate_number, basic.validators.validate_quantity]),
        ),
    ]
